version: '2'

services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - mynetwork
    ports:
      - "80:80"

networks:
  mynetwork:
    external: true  # Указываем, что сеть уже создана